"""Cart storage - backward compatibility wrapper.

This module re-exports from the new storage package for backward compatibility.
New code should import directly from app.storage package.
"""

from .storage import (
    DB_PATH,
    EVENT_TO_STAGE,
    MAX_CRM_MESSAGES,
    MAX_HISTORY_MESSAGES,
    STAGE_PRIORITY,
    add_chat_message,
    add_to_cart,
    cleanup_old_checkout_sessions,
    clear_cart,
    clear_chat_history,
    compute_cart_hash,
    compute_stage,
    format_messages_for_ai,
    get_ai_mode,
    get_cart,
    get_cart_count,
    get_cart_items_count,
    get_chat_history,
    get_daily_stats,
    get_first_seen,
    get_last_seen,
    get_or_create_checkout_session,
    get_user_events,
    get_user_messages,
    get_user_messages_count,
    get_user_orders_count,
    get_user_stage,
    has_user_consent,
    init_db,
    log_crm_event,
    log_crm_message,
    mark_checkout_complete,
    remove_from_cart,
    set_ai_mode,
    set_qty,
)

__all__ = [
    # Database
    "DB_PATH",
    "init_db",
    # Cart
    "add_to_cart",
    "set_qty",
    "remove_from_cart",
    "clear_cart",
    "get_cart",
    "get_cart_count",
    "get_cart_items_count",
    "compute_cart_hash",
    "get_or_create_checkout_session",
    "mark_checkout_complete",
    "cleanup_old_checkout_sessions",
    # Chat history
    "MAX_HISTORY_MESSAGES",
    "add_chat_message",
    "get_chat_history",
    "clear_chat_history",
    "set_ai_mode",
    "get_ai_mode",
    # CRM
    "STAGE_PRIORITY",
    "EVENT_TO_STAGE",
    "MAX_CRM_MESSAGES",
    "log_crm_event",
    "get_user_events",
    "get_user_stage",
    "get_user_orders_count",
    "get_daily_stats",
    "get_first_seen",
    "get_last_seen",
    "compute_stage",
    "log_crm_message",
    "get_user_messages",
    "get_user_messages_count",
    "has_user_consent",
    "format_messages_for_ai",
]
